#!/bin/sh

# create configure script - has been be done already so commented out
# ./autogen.sh
export JUDE2DIR=$HOME/jude2_install
export LD_LIBRARY_PATH=$JUDE2DIR/lib:$LD_LIBRARY_PATH
export PATH=$JUDE2DIR/bin:$PATH


# make a directory to build in
rm -rf build
mkdir -p build

touch aclocal.m4 Makefile.am configure Makefile.in


# change to that directory
cd build

# to build command line version only without qt use option --disable-qt
# remove --enable-optimised=yes to build without optimisation flags (may solve build problems but will run slower)
../configure --prefix=$JUDE2DIR --enable-optimised=yes --enable-openmp CFLAGS="-fopenmp" --disable-qt

# compile
make 

# copy to $JUDE2DIR, if under /usr/local you probably need root priviliges
# so if this fails try 'sudo make install'
make install


